root = "."
tmp_dir = "tmp"
[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/myapp"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "docs", "vendor"]
[run]
  cmd = "./tmp/main"
